//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FBD.Models
{
    [MetadataType(typeof(CustomersIndividualsMetaData))]
    public partial class CustomersIndividuals
    {
        public class CustomersIndividualsMetaData
        {
        		
        	[DisplayName("Individual ID")]
        	[Required]
            public int IndividualID { get; set; }
        		
        	[DisplayName("CIF")]
        	[Required]
            public decimal CIF { get; set; }
        		
        	[DisplayName("Customer Name")]
        	[StringLength(255)]
            public string CustomerName { get; set; }
        }
    }
}
